#!/usr/bin/env python3
"""
Generate the ship's idle "drift through space" animation.

Per CLAUDE.md, the base motion of any animated thing must come from a baked
clip in assets/animations/*.anim.json (procedural tweaks may be layered on
top). This script bakes the looping orbit + bob the corner-viewport ship plays
when the player is *not* actively driving it.

Output:
  - assets/animations/ship_idle.anim.json
  - src/ship_idle_anim.h          (baked C array used by the runtime)
"""

import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_JSON = os.path.join(ROOT, "assets", "animations", "ship_idle.anim.json")
OUT_H    = os.path.join(ROOT, "src", "ship_idle_anim.h")

# 240-frame loop at 60 Hz = 4 second cycle. Long-ish so the per-frame
# bob/sway feels gentle rather than oscillatory.
NUM_FRAMES = 240
FPS = 60
LOOP = True

# Bob amplitudes for the idle clip. The ship is meant to read as "drifting
# forward through space" — there is NO yaw rotation in the clip; forward
# motion is added procedurally on top by ship_view.c so the camera + stars
# track properly. Only subtle pitch/roll wobble + Y bob here.
BOB_AMP   = 0.18      # Y bob in local units (× ~14 = world units)
PITCH_AMP = 0.04      # radians (~2.3°)
ROLL_AMP  = 0.06      # radians (~3.4°)
SWAY_AMP  = 0.08      # tiny lateral sway in X (so the parallax isn't dead-straight)


def main() -> None:
    frames = []
    for i in range(NUM_FRAMES):
        t = (i / NUM_FRAMES) * 2.0 * math.pi
        # Position: stays near origin in XZ — the actual forward motion is
        # applied procedurally by ship_view.c. We just give a subtle bob and
        # tiny lateral sway here.
        px = math.sin(t) * SWAY_AMP
        py = math.sin(t * 1.5) * BOB_AMP
        pz = 0.0
        # Heading: zero yaw. The clip is "ship pointing straight forward".
        yaw = 0.0
        # Pitch / roll: gentle wobble, slightly out of phase so the motion
        # doesn't read as a single oscillation.
        pitch = math.sin(t * 1.5) * PITCH_AMP
        roll  = math.sin(t + 0.7) * ROLL_AMP
        frames.append({
            "pos":   [round(px, 4), round(py, 4), round(pz, 4)],
            "euler": [round(pitch, 4), round(yaw, 4), round(roll, 4)],
        })

    clip = {
        "name": "ship_idle",
        "fps": FPS,
        "loop": LOOP,
        "frames": frames,
    }

    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(clip, f, indent=2)

    # ---- Bake to C so the runtime can sample without parsing JSON.
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/gen-ship-anim.py. Do not edit by hand.")
    lines.append("// Regenerate: python3 tools/gen-ship-anim.py")
    lines.append("// Source: assets/animations/ship_idle.anim.json")
    lines.append("#ifndef SHIP_IDLE_ANIM_H")
    lines.append("#define SHIP_IDLE_ANIM_H")
    lines.append("")
    lines.append(f"#define SHIP_IDLE_NUM_FRAMES {NUM_FRAMES}")
    lines.append(f"#define SHIP_IDLE_FPS         {FPS}")
    lines.append(f"#define SHIP_IDLE_LOOP        {1 if LOOP else 0}")
    lines.append("")
    lines.append("// Each entry is { pos.x, pos.y, pos.z, pitch, yaw, roll }.")
    lines.append("static const float SHIP_IDLE_KEYFRAMES[SHIP_IDLE_NUM_FRAMES][6] = {")
    for fr in frames:
        p = fr["pos"]
        e = fr["euler"]
        lines.append(
            f"    {{{p[0]:.4f}f, {p[1]:.4f}f, {p[2]:.4f}f, "
            f"{e[0]:.4f}f, {e[1]:.4f}f, {e[2]:.4f}f}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("#endif // SHIP_IDLE_ANIM_H")
    lines.append("")

    with open(OUT_H, "w") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT_JSON}  ({NUM_FRAMES} frames @ {FPS} Hz)")
    print(f"wrote {OUT_H}")


if __name__ == "__main__":
    main()
