#!/usr/bin/env python3
"""
Bake assets/models/bridge_panel.obj into a C header so the runtime can link
the geometry as static data (no DFS load, no .obj parser at runtime).

Reads the canonical .obj file (per CLAUDE.md). Emits per-vertex int16 positions
(scaled by WORLD_SCALE), packed 16-bit UVs in tiny3d's 10.5 fixed-point format,
and a triangle list.
"""

import os
import re

WORLD_SCALE = 30  # 1 meter -> 30 game units (panel becomes ~30 units wide ~18 tall)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_OBJ = os.path.join(ROOT, "assets", "models", "bridge_panel.obj")
OUT_H   = os.path.join(ROOT, "src", "bridge_panel_model.h")


def parse_obj(path: str):
    verts: list[tuple[float, float, float]] = []
    uvs:   list[tuple[float, float]]        = []
    tris:  list[list[tuple[int, int]]]       = []  # [(v_idx, uv_idx), ...]
    with open(path) as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            tag, rest = parts[0], parts[1:]
            if tag == "v":
                verts.append((float(rest[0]), float(rest[1]), float(rest[2])))
            elif tag == "vt":
                uvs.append((float(rest[0]), float(rest[1])))
            elif tag == "f":
                # `f v/vt v/vt v/vt`  (we only emit triangles)
                tri = []
                for token in rest:
                    m = re.match(r"(\d+)/(\d+)", token)
                    assert m, f"unsupported face token: {token!r}"
                    tri.append((int(m.group(1)) - 1, int(m.group(2)) - 1))
                assert len(tri) == 3, "obj must be triangulated"
                tris.append(tri)
    return verts, uvs, tris


def main() -> None:
    verts, uvs, tris = parse_obj(SRC_OBJ)

    # Each triangle has 3 (v_idx, uv_idx) pairs. We unroll into per-corner
    # vertex records (position from verts[v_idx], uv from uvs[uv_idx]) so we
    # can map directly into T3DVertPacked at runtime without an indirection.
    corners: list[tuple[tuple[float, float, float], tuple[float, float]]] = []
    for tri in tris:
        for v_idx, uv_idx in tri:
            corners.append((verts[v_idx], uvs[uv_idx]))

    # Pack into 4-corner groups (quads), but our generator emitted 2 tris per
    # quad in order so corners[i*6 .. i*6+6] are one quad's two triangles.
    # We just emit verts for tris directly — the runtime will load 3 verts at
    # a time and draw a triangle with indices (0,1,2).

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/gen-bridge-panel-c.py. Do not edit by hand.")
    lines.append("// Regenerate: python3 tools/gen-bridge-panel-c.py")
    lines.append("#ifndef BRIDGE_PANEL_MODEL_H")
    lines.append("#define BRIDGE_PANEL_MODEL_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define BRIDGE_PANEL_NUM_TRIS  {len(tris)}")
    lines.append(f"#define BRIDGE_PANEL_NUM_VERTS {len(corners)}")
    lines.append("")
    # int16 positions (UV unpacked here; runtime packs with UV() macro from game_config.h)
    lines.append("static const int16_t BRIDGE_PANEL_POS[BRIDGE_PANEL_NUM_VERTS][3] = {")
    for (vx, vy, vz), _ in corners:
        x = round(vx * WORLD_SCALE)
        y = round(vy * WORLD_SCALE)
        z = round(vz * WORLD_SCALE)
        lines.append(f"    {{{x:5d}, {y:5d}, {z:5d}}},")
    lines.append("};")
    lines.append("")
    # UVs as floats in [0,1] — the C side multiplies by 32 (UV macro) at build.
    lines.append("// UVs are in [0,1] texture-space; runtime applies the 10.5 fixed-point scale.")
    lines.append("static const float BRIDGE_PANEL_UV[BRIDGE_PANEL_NUM_VERTS][2] = {")
    for _, (u, v) in corners:
        lines.append(f"    {{{u:.4f}f, {v:.4f}f}},")
    lines.append("};")
    lines.append("")
    # Per-triangle face normal so the C side gets flat shading without a
    # reload of the .obj at runtime. Compute from positions.
    def cross(a, b):
        return (
            a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0],
        )

    def sub(a, b):
        return (a[0] - b[0], a[1] - b[1], a[2] - b[2])

    def normalize(v):
        m = (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]) ** 0.5
        if m == 0:
            return (0.0, 1.0, 0.0)
        return (v[0] / m, v[1] / m, v[2] / m)

    lines.append("static const float BRIDGE_PANEL_TRI_NORMAL[BRIDGE_PANEL_NUM_TRIS][3] = {")
    for tri in tris:
        p0 = verts[tri[0][0]]
        p1 = verts[tri[1][0]]
        p2 = verts[tri[2][0]]
        n = normalize(cross(sub(p1, p0), sub(p2, p0)))
        lines.append(f"    {{{n[0]:.4f}f, {n[1]:.4f}f, {n[2]:.4f}f}},")
    lines.append("};")
    lines.append("")

    lines.append("#endif // BRIDGE_PANEL_MODEL_H")
    lines.append("")

    with open(OUT_H, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_H}  ({len(corners)} verts, {len(tris)} tris)")


if __name__ == "__main__":
    main()
