#!/usr/bin/env python3
"""
Generate the player-ship mesh shown in the corner viewport.

Writes:
  - assets/models/ship.obj   (canonical baked source-of-truth, per CLAUDE.md)
  - assets/models/ship.json  (sidecar for the model editor / C baker)

The ship is a chunky low-poly arrowhead: a wedge-shaped hull (top + bottom
faces sloping down toward the nose), two short side wings, and a flat tail.
UVs sample ship.png — the top-side band for upward-facing faces, the
underside band for downward-facing ones.
"""

import json
import os

GRID = 0.05
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_OBJ  = os.path.join(ROOT, "assets", "models", "ship.obj")
OUT_JSON = os.path.join(ROOT, "assets", "models", "ship.json")


def quad(face_list, vi, u_lo, u_hi, v_lo, v_hi):
    face_list.append((vi, (u_lo, u_hi, v_lo, v_hi)))


def main() -> None:
    # Hull along +Z (nose at +Z, tail at -Z). Coordinates in meters.
    verts = [
        # Hull body (wedge): tail rectangle + nose point
        # Tail face: 0..3 (rectangle, viewed from -Z)
        [-0.4, -0.10, -0.6],  # 0 tail-bot-left
        [ 0.4, -0.10, -0.6],  # 1 tail-bot-right
        [ 0.4,  0.15, -0.6],  # 2 tail-top-right
        [-0.4,  0.15, -0.6],  # 3 tail-top-left
        # Mid section (where wings attach): 4..7
        [-0.5, -0.08,  0.0],  # 4
        [ 0.5, -0.08,  0.0],  # 5
        [ 0.5,  0.18,  0.0],  # 6
        [-0.5,  0.18,  0.0],  # 7
        # Nose tip: pinch to a thin diamond at +Z
        [-0.05, 0.0,  0.7],   # 8 nose-bot-left
        [ 0.05, 0.0,  0.7],   # 9 nose-bot-right
        [ 0.05, 0.10, 0.7],   # 10 nose-top-right
        [-0.05, 0.10, 0.7],   # 11 nose-top-left
        # Left wing tip: 12, 13 (thin chord)
        [-1.0,  0.05, -0.15], # 12 wing-l-bot
        [-1.0,  0.10, -0.15], # 13 wing-l-top
        # Right wing tip: 14, 15
        [ 1.0,  0.05, -0.15], # 14
        [ 1.0,  0.10, -0.15], # 15
    ]

    faces: list = []

    # UV bands on ship.png:
    TOP_LO, TOP_HI = 0.02, 0.48     # top-side hull band (V 0..0.5)
    BOT_LO, BOT_HI = 0.52, 0.98     # underside band      (V 0.5..1)

    # ---- Tail face (-Z) — neutral, use top band so it reads as plating.
    quad(faces, [0, 1, 2, 3], 0.0, 1.0, TOP_LO, TOP_HI)

    # ---- Top hull (+Y), two segments tail->mid and mid->nose.
    quad(faces, [3, 2, 6, 7], 0.0, 0.5, TOP_LO, TOP_HI)   # tail->mid
    quad(faces, [7, 6, 10, 11], 0.5, 1.0, TOP_LO, TOP_HI) # mid->nose

    # ---- Bottom hull (-Y), tail->mid and mid->nose.
    quad(faces, [4, 5, 1, 0], 0.0, 0.5, BOT_LO, BOT_HI)   # tail->mid
    quad(faces, [8, 9, 5, 4], 0.5, 1.0, BOT_LO, BOT_HI)   # mid->nose

    # ---- Left side (-X): tail to mid (rectangle), mid to nose (triangle quad).
    quad(faces, [0, 3, 7, 4], 0.0, 0.5, TOP_LO, TOP_HI)        # tail->mid
    quad(faces, [4, 7, 11, 8], 0.5, 1.0, TOP_LO, TOP_HI)       # mid->nose

    # ---- Right side (+X).
    quad(faces, [1, 5, 6, 2], 0.0, 0.5, TOP_LO, TOP_HI)
    quad(faces, [5, 9, 10, 6], 0.5, 1.0, TOP_LO, TOP_HI)

    # ---- Wings: each wing is a thin quad sticking out from the hull side.
    # Left wing top face
    quad(faces, [13, 7, 4, 12], 0.2, 0.8, TOP_LO, TOP_HI)
    # Left wing bottom face
    quad(faces, [12, 4, 7, 13], 0.2, 0.8, BOT_LO, BOT_HI)
    # Right wing top face
    quad(faces, [6, 15, 14, 5], 0.2, 0.8, TOP_LO, TOP_HI)
    # Right wing bottom face
    quad(faces, [5, 14, 15, 6], 0.2, 0.8, BOT_LO, BOT_HI)

    # Snap.
    def snap(v):
        return round(round(v / GRID) * GRID, 4)
    verts = [[snap(c) for c in v] for v in verts]

    # ---- Write OBJ.
    os.makedirs(os.path.dirname(OUT_OBJ), exist_ok=True)
    with open(OUT_OBJ, "w") as f:
        f.write("# ship.obj — generated by tools/gen-ship.py\n")
        f.write("# UVs sample ship.png; bands documented in gen-textures.py\n")
        f.write("o ship\n")
        for v in verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        uv_index = 1
        face_uv_indices = []
        for vi, (u_lo, u_hi, v_lo, v_hi) in faces:
            corners = [(u_lo, v_lo), (u_hi, v_lo), (u_hi, v_hi), (u_lo, v_hi)]
            for u, v in corners:
                f.write(f"vt {u:.4f} {v:.4f}\n")
            face_uv_indices.append([uv_index, uv_index + 1, uv_index + 2, uv_index + 3])
            uv_index += 4
        for (vi, _uv), uv_idx in zip(faces, face_uv_indices):
            tris = [
                ([vi[0], vi[1], vi[2]], [uv_idx[0], uv_idx[1], uv_idx[2]]),
                ([vi[0], vi[2], vi[3]], [uv_idx[0], uv_idx[2], uv_idx[3]]),
            ]
            for tri_v, tri_uv in tris:
                f.write(
                    f"f {tri_v[0]+1}/{tri_uv[0]} "
                    f"{tri_v[1]+1}/{tri_uv[1]} "
                    f"{tri_v[2]+1}/{tri_uv[2]}\n"
                )

    sidecar = {
        "name": "ship",
        "grid": GRID,
        "vertices": verts,
        "faces": [
            {
                "vertices": vi,
                "uv": {"u_lo": u_lo, "u_hi": u_hi, "v_lo": v_lo, "v_hi": v_hi},
            }
            for vi, (u_lo, u_hi, v_lo, v_hi) in faces
        ],
    }
    with open(OUT_JSON, "w") as f:
        json.dump(sidecar, f, indent=2)

    print(f"wrote {OUT_OBJ}  ({len(verts)} verts, {len(faces)} quads)")
    print(f"wrote {OUT_JSON}")


if __name__ == "__main__":
    main()
