#!/usr/bin/env python3
"""
Generate the bridge control-panel mesh.

Writes both a baked Wavefront OBJ at assets/models/bridge_panel.obj (canonical
source-of-truth — see CLAUDE.md) and a JSON sidecar for the in-browser model
editor. The accompanying C header is emitted by tools/gen-bridge-panel-c.py.

The panel is a small low-poly console: a wedge-shaped body (top face slanted
toward the player), a recessed display, two button rows on the slanted top,
and an impulse throttle slot on the front face.

UV layout matches the bridge_panel.png atlas bands (see gen-textures.py):
  band 0 (V 0.00..0.25): main display
  band 1 (V 0.25..0.50): button caps
  band 2 (V 0.50..0.75): metal body
  band 3 (V 0.75..1.00): throttle slot
"""

import json
import os
from typing import List, Tuple

GRID = 0.05  # 5 cm snap — finer than character (10 cm) so we get the wedge shape clean
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_OBJ  = os.path.join(ROOT, "assets", "models", "bridge_panel.obj")
OUT_JSON = os.path.join(ROOT, "assets", "models", "bridge_panel.json")


# Per-face UV band selection. Each entry is (v_lo, v_hi) in [0,1].
BAND_DISPLAY  = (0.02, 0.23)
BAND_BUTTONS  = (0.27, 0.48)
BAND_METAL    = (0.52, 0.73)
BAND_THROTTLE = (0.77, 0.98)


# A face is (vertex-index list, (u_lo, u_hi, v_lo, v_hi)). Vertex indices are
# into the `verts` list below. Each face is a quad emitted as 2 triangles.
def quad_face(vi: List[int], u_lo: float, u_hi: float, band: Tuple[float, float]):
    v_lo, v_hi = band
    return (vi, (u_lo, u_hi, v_lo, v_hi))


def main() -> None:
    # ---- Vertex layout --------------------------------------------------
    # The console is a 1.0 x 0.6 x 0.5 (W x H x D) wedge:
    #
    #          (top, slanted toward -Z / player)
    #    7----------6
    #   /|         /|
    #  4----------5 |
    #  | 3--------|-2
    #  |/         |/
    #  0----------1
    #
    # x in [-0.5, +0.5], z in [-0.25, +0.25] (front face is -Z = toward player),
    # bottom y=0, back-top y=0.6, front-top y=0.45 (slanted toward player so
    # the operator can see the screen + reach the buttons).
    verts = [
        [-0.5, 0.00, -0.25],  # 0  front-bottom-left
        [ 0.5, 0.00, -0.25],  # 1  front-bottom-right
        [ 0.5, 0.00,  0.25],  # 2  back-bottom-right
        [-0.5, 0.00,  0.25],  # 3  back-bottom-left
        [-0.5, 0.45, -0.25],  # 4  front-top-left   (slanted lower)
        [ 0.5, 0.45, -0.25],  # 5  front-top-right
        [ 0.5, 0.60,  0.25],  # 6  back-top-right
        [-0.5, 0.60,  0.25],  # 7  back-top-left
    ]

    faces: list = []

    # Bottom (-Y) — metal, full band, doesn't matter much (hidden against floor).
    faces.append(quad_face([0, 1, 2, 3], 0.0, 1.0, BAND_METAL))

    # Back (+Z) — metal panels, full band.
    faces.append(quad_face([3, 2, 6, 7], 0.0, 1.0, BAND_METAL))

    # Left (-X) — metal.
    faces.append(quad_face([0, 3, 7, 4], 0.0, 1.0, BAND_METAL))

    # Right (+X) — metal.
    faces.append(quad_face([1, 5, 6, 2], 0.0, 1.0, BAND_METAL))

    # Top (slanted, +Y) — this is the *operator-facing* slanted face.
    # Split it into two regions stacked along the slant: a display area
    # near the back and a button row near the front. We do that by
    # introducing two extra vertices halfway across the slant (verts 8/9).
    # 8 is the midpoint of the 4-7 edge, 9 is the midpoint of the 5-6 edge.
    mid_l = [(-0.5),
             (0.45 + 0.60) * 0.5,
             ( -0.25 + 0.25) * 0.5]
    mid_r = [( 0.5),
             (0.45 + 0.60) * 0.5,
             ( -0.25 + 0.25) * 0.5]
    verts.append(mid_l)  # 8
    verts.append(mid_r)  # 9
    # Back half of the slant (between mid line and back edge) = display.
    faces.append(quad_face([8, 9, 6, 7], 0.0, 1.0, BAND_DISPLAY))
    # Front half of the slant (between front edge and mid line) = buttons.
    faces.append(quad_face([4, 5, 9, 8], 0.0, 1.0, BAND_BUTTONS))

    # Front (-Z) — throttle slot band on the lower 1/2, metal on upper 1/2.
    # Split via two extra mid-height verts on the front face.
    front_mid_y = 0.22
    verts.append([-0.5, front_mid_y, -0.25])  # 10
    verts.append([ 0.5, front_mid_y, -0.25])  # 11
    # Lower half = throttle.
    faces.append(quad_face([0, 1, 11, 10], 0.0, 1.0, BAND_THROTTLE))
    # Upper half = metal.
    faces.append(quad_face([10, 11, 5, 4], 0.0, 1.0, BAND_METAL))

    # ---- Snap + write ---------------------------------------------------
    def snap(v: float) -> float:
        return round(round(v / GRID) * GRID, 4)

    verts = [[snap(c) for c in v] for v in verts]

    # Triangulate quads to (v0,v1,v2) (v0,v2,v3) and emit OBJ.
    os.makedirs(os.path.dirname(OUT_OBJ), exist_ok=True)
    with open(OUT_OBJ, "w") as f:
        f.write("# bridge_panel.obj — generated by tools/gen-bridge-panel.py\n")
        f.write("# UVs sample bridge_panel.png; bands documented in gen-textures.py\n")
        f.write("o bridge_panel\n")
        for v in verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        # Emit unique UVs per face corner so adjacent faces don't share UVs.
        uv_index = 1
        face_uv_indices: list[list[int]] = []
        for vi, (u_lo, u_hi, v_lo, v_hi) in faces:
            corners = [
                (u_lo, v_lo),
                (u_hi, v_lo),
                (u_hi, v_hi),
                (u_lo, v_hi),
            ]
            for u, v in corners:
                f.write(f"vt {u:.4f} {v:.4f}\n")
            face_uv_indices.append([uv_index, uv_index + 1, uv_index + 2, uv_index + 3])
            uv_index += 4
        # Triangulate.
        triangles_meta: list[tuple[list[int], list[int]]] = []  # (v_indices, uv_indices)
        for (vi, _uv), uv_idx in zip(faces, face_uv_indices):
            tri_a_v  = [vi[0], vi[1], vi[2]]
            tri_a_uv = [uv_idx[0], uv_idx[1], uv_idx[2]]
            tri_b_v  = [vi[0], vi[2], vi[3]]
            tri_b_uv = [uv_idx[0], uv_idx[2], uv_idx[3]]
            for tri_v, tri_uv in ((tri_a_v, tri_a_uv), (tri_b_v, tri_b_uv)):
                # OBJ is 1-indexed; verts list is 0-indexed.
                f.write(
                    f"f {tri_v[0]+1}/{tri_uv[0]} "
                    f"{tri_v[1]+1}/{tri_uv[1]} "
                    f"{tri_v[2]+1}/{tri_uv[2]}\n"
                )
                triangles_meta.append((tri_v, tri_uv))

    # JSON sidecar (for the model editor + the C generator).
    sidecar = {
        "name": "bridge_panel",
        "grid": GRID,
        "vertices": verts,
        "faces": [
            {
                "vertices": vi,
                "uv": {"u_lo": u_lo, "u_hi": u_hi, "v_lo": v_lo, "v_hi": v_hi},
            }
            for vi, (u_lo, u_hi, v_lo, v_hi) in faces
        ],
    }
    with open(OUT_JSON, "w") as f:
        json.dump(sidecar, f, indent=2)

    print(f"wrote {OUT_OBJ}  ({len(verts)} verts, {len(faces)} quads)")
    print(f"wrote {OUT_JSON}")


if __name__ == "__main__":
    main()
