#!/usr/bin/env python3
"""
Bake assets/models/fighter.obj (+ fighter.json) into a C header.

The fighter renders with RDPQ_COMBINER_SHADE (no texture), so the bake emits
positions + flat per-tri normals + a per-face rgba. Same general shape as
gen-ship-c.py, just with colour rows instead of UVs.

Output: src/fighter_model.h.
"""

import json
import os
import re

WORLD_SCALE = 14   # match SHIP_WORLD_SCALE so the fighter sits at a sensible
                   # in-game size (~14 units long, comparable to the player ship)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_OBJ  = os.path.join(ROOT, "assets", "models", "fighter.obj")
SRC_JSON = os.path.join(ROOT, "assets", "models", "fighter.json")
OUT_H    = os.path.join(ROOT, "src", "fighter_model.h")


def parse_obj(path: str):
    verts: list[tuple[float, float, float]] = []
    tris:  list[list[int]] = []
    with open(path) as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            tag, rest = parts[0], parts[1:]
            if tag == "v":
                verts.append((float(rest[0]), float(rest[1]), float(rest[2])))
            elif tag == "f":
                tri = []
                for token in rest:
                    # OBJ "v" or "v/vt" both supported — fighter.obj writes
                    # plain "v" indices, but be lenient.
                    m = re.match(r"(\d+)(?:/\d*)?", token)
                    assert m, f"unsupported face token: {token!r}"
                    tri.append(int(m.group(1)) - 1)
                assert len(tri) == 3, "obj must be triangulated"
                tris.append(tri)
    return verts, tris


def hex_to_rgba(s: str):
    s = s.strip().lstrip("#")
    if len(s) == 6:
        s += "FF"
    assert len(s) == 8, f"bad rgba hex: {s!r}"
    return tuple(int(s[i:i+2], 16) for i in (0, 2, 4, 6))


def main() -> None:
    verts, tris = parse_obj(SRC_OBJ)
    with open(SRC_JSON) as f:
        sidecar = json.load(f)

    # Each sidecar quad expanded to two tris (in the same order gen-fighter.py
    # writes them to the .obj). Filter out collapsed degenerate tris so we
    # don't waste a draw call.
    quad_colors = [face["color"] for face in sidecar["faces"]]
    expanded: list[tuple[list[int], tuple[int, int, int, int]]] = []
    tri_idx = 0
    for face in sidecar["faces"]:
        col = hex_to_rgba(face["color"])
        for offset in range(2):
            tri = tris[tri_idx]
            tri_idx += 1
            # Collapsed (any two equal indices) — skip.
            if tri[0] == tri[1] or tri[1] == tri[2] or tri[0] == tri[2]:
                continue
            expanded.append((tri, col))
    assert tri_idx == len(tris), \
        f"obj/json face count mismatch: {tri_idx} vs {len(tris)}"

    # Per-tri flat normals from the cross product of edges.
    def cross(a, b):
        return (
            a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0],
        )
    def sub(a, b):
        return (a[0] - b[0], a[1] - b[1], a[2] - b[2])
    def normalize(v):
        m = (v[0]*v[0] + v[1]*v[1] + v[2]*v[2]) ** 0.5
        if m == 0:
            return (0.0, 1.0, 0.0)
        return (v[0]/m, v[1]/m, v[2]/m)

    # Each tri contributes 3 corners (pos, color); store flat.
    corners_pos: list[tuple[float, float, float]] = []
    corners_rgba: list[tuple[int, int, int, int]] = []
    tri_normals: list[tuple[float, float, float]] = []
    for tri, col in expanded:
        for v_idx in tri:
            corners_pos.append(verts[v_idx])
            corners_rgba.append(col)
        p0, p1, p2 = (verts[tri[i]] for i in range(3))
        n = normalize(cross(sub(p1, p0), sub(p2, p0)))
        tri_normals.append(n)

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/gen-fighter-c.py. Do not edit by hand.")
    lines.append("// Regenerate: python3 tools/gen-fighter-c.py")
    lines.append("#ifndef FIGHTER_MODEL_H")
    lines.append("#define FIGHTER_MODEL_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define FIGHTER_NUM_TRIS  {len(expanded)}")
    lines.append(f"#define FIGHTER_NUM_VERTS {len(corners_pos)}")
    lines.append("")
    lines.append("static const int16_t FIGHTER_POS[FIGHTER_NUM_VERTS][3] = {")
    for (vx, vy, vz) in corners_pos:
        x = round(vx * WORLD_SCALE)
        y = round(vy * WORLD_SCALE)
        z = round(vz * WORLD_SCALE)
        lines.append(f"    {{{x:5d}, {y:5d}, {z:5d}}},")
    lines.append("};")
    lines.append("")
    # Pack rgba8888 in big-endian byte order (R, G, B, A) so the runtime
    # can consume it directly as a uint32_t literal — same convention as
    # the existing 0xRRGGBBAA hex constants in src/meshes.c.
    lines.append("static const uint32_t FIGHTER_RGBA[FIGHTER_NUM_VERTS] = {")
    for (r, g, b, a) in corners_rgba:
        packed = (r << 24) | (g << 16) | (b << 8) | a
        lines.append(f"    0x{packed:08X}u,")
    lines.append("};")
    lines.append("")
    lines.append("static const float FIGHTER_TRI_NORMAL[FIGHTER_NUM_TRIS][3] = {")
    for n in tri_normals:
        lines.append(f"    {{{n[0]:.4f}f, {n[1]:.4f}f, {n[2]:.4f}f}},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // FIGHTER_MODEL_H")
    lines.append("")

    with open(OUT_H, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_H}  ({len(corners_pos)} verts, {len(expanded)} tris)")


if __name__ == "__main__":
    main()
