#!/usr/bin/env python3
"""
Bake assets/models/character.json into a C header so the N64 build can link
the character geometry as static data (no DFS load, no parser at runtime).

Character JSON units are meters (head at y=1.6). We scale by WORLD_SCALE so the
result fits the existing int16 position convention used by meshes.c.
"""

import json
import os

WORLD_SCALE = 10  # 1 meter → 10 game units; character becomes 16 units tall
SRC_JSON = os.path.join(os.path.dirname(__file__), "..", "assets", "models", "character.json")
OUT_H = os.path.join(os.path.dirname(__file__), "..", "src", "character_model.h")


def main() -> None:
    with open(SRC_JSON) as f:
        model = json.load(f)

    verts = model["vertices"]
    tris = model["triangles"]
    parts = model["parts"]

    # Sanity: every part is 8 verts / 12 tris in cube topology.
    # We emit per-part vertex blocks so the runtime can render them one cube
    # at a time (keeps us well under tiny3d's internal vertex buffer limit).
    assert all(p["vertex_count"] == 8 for p in parts), "expected 8 verts per part"

    # Re-group triangles by owning part (a tri belongs to the part whose
    # vertex_start..vertex_start+8 range contains all three indices).
    part_tris: list[list[tuple[int, int, int]]] = [[] for _ in parts]
    for tri in tris:
        for pi, p in enumerate(parts):
            start = p["vertex_start"]
            if all(start <= i < start + 8 for i in tri):
                # Emit relative indices within the part.
                part_tris[pi].append(tuple(i - start for i in tri))
                break
        else:
            raise RuntimeError(f"triangle {tri} spans multiple parts")
    assert all(len(t) == 12 for t in part_tris), "expected 12 tris per part"

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/gen-character-c.py. Do not edit by hand.")
    lines.append("// Regenerate: python3 tools/gen-character-c.py")
    lines.append("#ifndef CHARACTER_MODEL_H")
    lines.append("#define CHARACTER_MODEL_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define CHARACTER_NUM_PARTS {len(parts)}")
    lines.append("#define CHARACTER_VERTS_PER_PART 8")
    lines.append("#define CHARACTER_TRIS_PER_PART 12")
    lines.append("")

    # Part names (useful for debugging / UV band lookup)
    names = ", ".join(f'"{p["name"]}"' for p in parts)
    lines.append(f"static const char *CHARACTER_PART_NAMES[CHARACTER_NUM_PARTS] = {{ {names} }};")
    lines.append("")

    # Position data: int16 per axis, scaled
    lines.append("static const int16_t CHARACTER_PART_POS[CHARACTER_NUM_PARTS][CHARACTER_VERTS_PER_PART][3] = {")
    for p in parts:
        lines.append(f"    // {p['name']}")
        lines.append("    {")
        for i in range(8):
            v = verts[p["vertex_start"] + i]
            x = round(v[0] * WORLD_SCALE)
            y = round(v[1] * WORLD_SCALE)
            z = round(v[2] * WORLD_SCALE)
            lines.append(f"        {{{x:5d}, {y:5d}, {z:5d}}},")
        lines.append("    },")
    lines.append("};")
    lines.append("")

    # Triangle topology (same for every cube but emit per-part for clarity)
    lines.append("static const uint8_t CHARACTER_PART_TRIS[CHARACTER_NUM_PARTS][CHARACTER_TRIS_PER_PART][3] = {")
    for pi, p in enumerate(parts):
        lines.append(f"    // {p['name']}")
        lines.append("    {")
        for tri in part_tris[pi]:
            lines.append(f"        {{{tri[0]}, {tri[1]}, {tri[2]}}},")
        lines.append("    },")
    lines.append("};")
    lines.append("")

    lines.append("#endif // CHARACTER_MODEL_H")
    lines.append("")

    with open(OUT_H, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_H}  ({len(parts)} parts × 8 verts, {len(parts)*12} tris total)")


if __name__ == "__main__":
    main()
