#!/usr/bin/env python3
"""
Bake the character's walk cycle to an animation file.

The runtime in src/character.c layers a smoothed phase blend on top of a base
sine swing so it can ease in/out of the cycle as the stick velocity changes.
Per CLAUDE.md, the *base motion* must come from a baked clip — that's this
file. (The runtime smoothing is a procedural tweak on top.)

Output:
  - assets/animations/character_walk.anim.json
  - src/character_walk_anim.h
"""

import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_JSON = os.path.join(ROOT, "assets", "animations", "character_walk.anim.json")
OUT_H    = os.path.join(ROOT, "src", "character_walk_anim.h")

NUM_FRAMES = 32           # one full cycle
FPS = 60
LOOP = True
LEG_AMP = 0.52            # radians (~30°), matches WALK_SWING_LEG in character.c
ARM_AMP = 0.44            # radians (~25°), matches WALK_SWING_ARM


def main() -> None:
    frames = []
    for i in range(NUM_FRAMES):
        phase = (i / NUM_FRAMES) * 2.0 * math.pi
        s = math.sin(phase)
        leg_l = round(  s * LEG_AMP, 4)
        leg_r = round( -s * LEG_AMP, 4)
        arm_l = round( -s * ARM_AMP, 4)
        arm_r = round(  s * ARM_AMP, 4)
        frames.append({
            "leg_l_pitch": leg_l,
            "leg_r_pitch": leg_r,
            "arm_l_pitch": arm_l,
            "arm_r_pitch": arm_r,
        })

    clip = {
        "name": "character_walk",
        "fps": FPS,
        "loop": LOOP,
        "bones": ["leg_l", "leg_r", "arm_l", "arm_r"],
        "frames": frames,
    }
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(clip, f, indent=2)

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/gen-character-anim.py. Do not edit by hand.")
    lines.append("// Regenerate: python3 tools/gen-character-anim.py")
    lines.append("// Source: assets/animations/character_walk.anim.json")
    lines.append("#ifndef CHARACTER_WALK_ANIM_H")
    lines.append("#define CHARACTER_WALK_ANIM_H")
    lines.append("")
    lines.append(f"#define CHARACTER_WALK_NUM_FRAMES {NUM_FRAMES}")
    lines.append(f"#define CHARACTER_WALK_FPS         {FPS}")
    lines.append("")
    lines.append("// {leg_l_pitch, leg_r_pitch, arm_l_pitch, arm_r_pitch} (radians)")
    lines.append("static const float CHARACTER_WALK_KEYFRAMES[CHARACTER_WALK_NUM_FRAMES][4] = {")
    for fr in frames:
        lines.append(
            f"    {{{fr['leg_l_pitch']:.4f}f, {fr['leg_r_pitch']:.4f}f, "
            f"{fr['arm_l_pitch']:.4f}f, {fr['arm_r_pitch']:.4f}f}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("#endif // CHARACTER_WALK_ANIM_H")
    lines.append("")
    with open(OUT_H, "w") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_H}")


if __name__ == "__main__":
    main()
