// AUTO-GENERATED by tools/gen-character-anim.py. Do not edit by hand.
// Regenerate: python3 tools/gen-character-anim.py
// Source: assets/animations/character_walk.anim.json
#ifndef CHARACTER_WALK_ANIM_H
#define CHARACTER_WALK_ANIM_H

#define CHARACTER_WALK_NUM_FRAMES 32
#define CHARACTER_WALK_FPS         60

// {leg_l_pitch, leg_r_pitch, arm_l_pitch, arm_r_pitch} (radians)
static const float CHARACTER_WALK_KEYFRAMES[CHARACTER_WALK_NUM_FRAMES][4] = {
    {0.0000f, -0.0000f, -0.0000f, 0.0000f},
    {0.1014f, -0.1014f, -0.0858f, 0.0858f},
    {0.1990f, -0.1990f, -0.1684f, 0.1684f},
    {0.2889f, -0.2889f, -0.2445f, 0.2445f},
    {0.3677f, -0.3677f, -0.3111f, 0.3111f},
    {0.4324f, -0.4324f, -0.3658f, 0.3658f},
    {0.4804f, -0.4804f, -0.4065f, 0.4065f},
    {0.5100f, -0.5100f, -0.4315f, 0.4315f},
    {0.5200f, -0.5200f, -0.4400f, 0.4400f},
    {0.5100f, -0.5100f, -0.4315f, 0.4315f},
    {0.4804f, -0.4804f, -0.4065f, 0.4065f},
    {0.4324f, -0.4324f, -0.3658f, 0.3658f},
    {0.3677f, -0.3677f, -0.3111f, 0.3111f},
    {0.2889f, -0.2889f, -0.2445f, 0.2445f},
    {0.1990f, -0.1990f, -0.1684f, 0.1684f},
    {0.1014f, -0.1014f, -0.0858f, 0.0858f},
    {0.0000f, -0.0000f, -0.0000f, 0.0000f},
    {-0.1014f, 0.1014f, 0.0858f, -0.0858f},
    {-0.1990f, 0.1990f, 0.1684f, -0.1684f},
    {-0.2889f, 0.2889f, 0.2445f, -0.2445f},
    {-0.3677f, 0.3677f, 0.3111f, -0.3111f},
    {-0.4324f, 0.4324f, 0.3658f, -0.3658f},
    {-0.4804f, 0.4804f, 0.4065f, -0.4065f},
    {-0.5100f, 0.5100f, 0.4315f, -0.4315f},
    {-0.5200f, 0.5200f, 0.4400f, -0.4400f},
    {-0.5100f, 0.5100f, 0.4315f, -0.4315f},
    {-0.4804f, 0.4804f, 0.4065f, -0.4065f},
    {-0.4324f, 0.4324f, 0.3658f, -0.3658f},
    {-0.3677f, 0.3677f, 0.3111f, -0.3111f},
    {-0.2889f, 0.2889f, 0.2445f, -0.2445f},
    {-0.1990f, 0.1990f, 0.1684f, -0.1684f},
    {-0.1014f, 0.1014f, 0.0858f, -0.0858f},
};

#endif // CHARACTER_WALK_ANIM_H
